drop table if exists app;
drop table if exists domain;
drop table if exists link_outside;
drop table if exists namelist_link;
drop table if exists piping_extend;
drop table if exists proxy;
drop table if exists setting ;
drop table if exists site;
drop table if exists task;
drop table if exists task_execute;
drop table if exists task_notify;
drop table if exists task_piping;
drop table if exists task_piping_result;
drop table if exists task_piping_snapshot;
